  
name: geo_env
channels:
  - conda-forge
dependencies:
  - numpy
  - pysal
  - libpysal
  - matplotlib
  - geopandas
  - splot
  - esda
  - scikit-image
  - scikit-learn
  - pandana
  - urbanaccess
